#! /bin/sh
# depends of ghostscript pdftk wkhtmltopdf texlive-latex-base textlive-generic-recommended

usage(){
	echo "Usage: $(basename "$0") DATE_FIRST DATE_LAST DEST_DIR" >&2
	echo "       DATE FORMAT: AAAA-MM-DD" >&2
	exit 1
}

get_eval(){
	sed -ne "/>Avaluació<\/div>/,+1p" "$1" |tail -1 |sed -e "s%^.*>\(.\+\)<\/div.*$%\1%"
}
get_group(){
	sed -ne "/>Grup<\/div>/,+1p" "$1" |tail -1 |sed -e "s%^.*>\(.\+\)<\/div.*$%\1%"
}


[ "$1" ] || usage
DATE1="$1"
shift
[ "$1" ] || usage
DATE2="$1"
shift
[ "$1" ] || usage
DEST_DIR="$1"
[ -d "$DEST_DIR" ] || usage
PM_DIR="/opt/processmaker/shared/sites/ausias_wf/files"
echo "find . -type f -newermt $DATE1 ! -newermt $DATE2"
find $PM_DIR -type f -newermt $DATE1 ! -newermt $DATE2 -name "*doc" |while read f; do
	echo "$(get_group "$f")_Eval$(get_eval "$f") $f"
done

#for f in $(find . -type f -newermt 2017-06-14 ! -newermt 2017-06-16 ) ; do cp "$f" /home/depinf/eval-final/ ; done

