#! /bin/sh
# depends of ghostscript pdftk wkhtmltopdf texlive-latex-base textlive-generic-recommended

usage(){
	echo "Usage: $(basename "$0") DATE_FIRST DATE_LAST DEST_DIR" >&2
	echo "       DATE FORMAT: AAAA-MM-DD" >&2
	exit 1
}

get_eval(){
	sed -ne "/>Avaluació<\/div>/,+1p" "$1" |tail -1 |sed -e "s%^.*>\(.\+\)<\/div.*$%\1%"
}
get_group(){
	sed -ne "/>Grup<\/div>/,+1p" "$1" |tail -1 |sed -e "s%^.*>\(.\+\)<\/div.*$%\1%"
}

list_files(){
	find $PM_DIR -type f -newermt $DATE1 ! -newermt $DATE2 -name "*doc" -printf "%A+ %p\n" |while read d f; do
		echo "$(get_group "$f") Eval$(get_eval "$f") ${d} $f"
	done
}

[ "$1" ] || usage
DATE1="$1"
shift
[ "$1" ] || usage
DATE2="$1"
shift
[ "$1" ] || usage
DEST_DIR="$1"
[ -d "$DEST_DIR" ] || usage
PM_DIR="/opt/processmaker/shared/sites/ausias_wf/files"
echo "find . -type f -newermt $DATE1 ! -newermt $DATE2"
list_files |while read g e d f; do
	D="$(echo "$d" |tr "+:" "_-")"
	cp "$f" "$DEST_DIR/${g}_${e}_${D}.html"
done
# TODO: copy to temporary dir an do filter like this:
# ls -lS *html |sed -e "s%^.* %%" |while read f; do g="$(echo "$f" |cut -d "_" -f1,2)"; if [ -r "good/$g.html" ] ; then cp "$f" "pruebas/$f" ; else cp "$f" "good/$g.html" ; fi; done

#for f in $(find . -type f -newermt 2017-06-14 ! -newermt 2017-06-16 ) ; do cp "$f" /home/depinf/eval-final/ ; done

