#!/bin/sh
# common code ...
#requires: zip mysql-client

die() {
        echo "$1" >&2
        exit 1
}

usage(){
	die "Usage: $(basename "$0") PDF_DIR MSG_DIR SUBJECT"
}

user_confirmation(){
	preview_message "$1"
	echo "¿Do you want to proceed? (Y/N)"
        read a
        [ "$a" = "YES" ] || [ "$a" = "Y" ] || [ "$a" = "yes" ] || [ "$a" = "y" ] || return 1
	return 0
}

get_from_db(){
        DB_FIELD="$1"
        DB_LOGIN="$2"
        [ "$DB_LOGIN" ] || DB_LOGIN="$login"
        mysql -N -B -e "use itaca; select $DB_FIELD from alumnos where login='$DB_LOGIN'"
}

get_login_names(){
	GRUPO="$1"
	SQL="use simple_itaca; SELECT login FROM grupoasiprof_pm WHERE grupo='$GRUPO';"
	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
}

get_profes(){
	SQL="use simple_itaca; SELECT login FROM profesores_pm WHERE activo='1';"
	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
#	for l in svillanuevag lgarciag; do echo $l; done
#	for l in svillanuevag; do echo $l; done
#	cat lista_pendientes.txt

}

get_grupos(){
	PROFE="$1"
	SQL="use simple_itaca; SELECT grupo FROM grupoasiprof_pm WHERE login='$PROFE';"
	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u

}

get_group_by_fam(){
	FAMILIA="$1"
	SQL="use simple_itaca; SELECT codigo FROM grupos_pm WHERE familia='$FAMILIA';"
	mysql $PROCESSMAKER -N -B -e "$SQL" |sort -u
}

send_mail(){
	EMAIL_ADDRESS="$1"
	SUBJECT="$2"
	MSG_TXT="$3"
	shift 3
	EMAIL_CMD1="mutt"
	EMAIL_CMD2="${EMAIL_ADDRESS}@ausiasmarch.net "
	FILE_LIST=""
	for f in "$@"; do
		EMAIL_CMD2="$EMAIL_CMD2 -a $f"
		FILE_LIST="$FILE_LIST $(basename "$f")"
	done
	echo "Sending to $EMAIL_ADDRESS files: $FILE_LIST"
	rc=0
	REPLYTO="tic@ausiasmarch.net" $EMAIL_CMD1 -s "$SUBJECT" $EMAIL_CMD2 < $MSG_TXT || rc=$?
	return $rc
}

preview_message(){
	MSG_TXT="$1"
	echo "Please, verify the email message for $(basename $MSG_TXT)"
	echo ""
	echo "======================================================================================="
	echo "SUBJECT: $SUBJECT"
	echo ""
	cat $MSG_TXT
	echo "======================================================================================="

}

# basic tests
[ "$(id -un)" = "depinf" ] || die "You must be depinf to run this script"

# check configuration files
[ -r $HOME/.my.cnf ] || die "Missing mysql configurarion in $HOME/.my.cnf"

[ -r $HOME/.muttrc ] || die "Missing mutt configurarion in $HOME/.muttrc"

PDF_DIR="$1"

[ "$1" ] || usage
[ -d "$1" ] || die "$1 s not a directory"

[ $(ls "$PDF_DIR/" |grep "^[[:digit:]][[:alpha:]]\{4\}_Eval.*\.pdf$" |wc -l) -gt 0 ] || die "There is no pdf files in directory"
shift
[ "$1" ] || usage
MSG_DIR="$1"
PROF_TXT="$MSG_DIR/profesores.txt"
JDEP_TXT="$MSG_DIR/jdep.txt"
DIRE_TXT="$MSG_DIR/direccion.txt"
[ -d "$MSG_DIR" ] || die "Message directory invalid"
[ -s "$PROF_TXT" ] || die "Message file invalid (profesores)"
[ -s "$JDEP_TXT" ] || die "Message file invalid (jdep)"
[ -s "$DIRE_TXT" ] || die "Message file invalid (direccion)"

shift
[ "$1" ] || usage
SUBJECT=$*

PROCESSMAKER="-h 172.24.0.10"
LISTA_FAM="SAN,capsan COM,capcom ADM,capadm INF,capinf"
LISTA_DIR="capestudis"

if user_confirmation $PROF_TXT; then
	get_profes |while read profe; do
		LISTA_GRUPOS="$(get_grupos "$profe")"
		#echo "$profe: $LISTA_GRUPOS"
		LISTA_PDF=""
		for g in $LISTA_GRUPOS; do
			LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
		done
		if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
			send_mail "$profe" "$SUBJECT" "$PROF_TXT" $LISTA_PDF
		fi
	done
fi

if user_confirmation $JDEP_TXT; then

	TMP_DIR="$(mktemp -d)"

	for i in $LISTA_FAM; do
		FAMILIA=${i%,*}
		JDEP=${i#*,}
		echo $FAMILIA $JDEP
		LISTA_PDF=""
		for g in $(get_group_by_fam $FAMILIA); do
			LISTA_PDF="$LISTA_PDF $(ls -1 $PDF_DIR/${g}_Eval*.pdf 2>/dev/null)"
		done
		if ! echo "$LISTA_PDF" |grep -q "^[[:blank:]]*$" ; then
			ZIP_FILE="$TMP_DIR/actas_eval_$FAMILIA_$(date "+%m-%Y").zip"
			zip -r -j $ZIP_FILE $LISTA_PDF >/dev/null
			send_mail "$JDEP" "$SUBJECT" "$JDEP_TXT" "$ZIP_FILE"
		fi
	done
	rm -fr "$TMP_DIR"
fi

#TODO: falta hacer el bloque de los jefes de estudios
